development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: babysworld_development
  pool: 5
  username: root
  password: '0000'
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: babysworld_test
  pool: 5
  username: root
  password: '0000'
  socket: /tmp/mysql.sock

staging:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: babysworld_test
  pool: 5
  username: root
  password: '0000'
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: babysworld_production
  pool: 5
  username: root
  password: '0000'
  socket: /tmp/mysql.sock
